
@apiURL=http://localhost:8080
#@apiURL={{$dotenv API_URL}}
@token={{$dotenv TEMP_JWT_TOKEN}}

###
GET {{apiURL}}/boards
Authorization: Bearer {{token}}

###
POST {{apiURL}}/boards
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Board 2"
}