#@apiURL={{$dotenv API_URL}}
@apiURL=http://localhost:8080
@token={{$dotenv TEMP_JWT_TOKEN}}
@otherToken={{$dotenv OTHER_JWT_TOKEN}}
@boardId=valid_note_id

###
GET {{apiURL}}/boards
Authorization: Bearer {{token}}

###
POST {{apiURL}}/boards
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Testboard"
}

###
POST {{apiURL}}/boards/{{boardId}}/invite
Content-Type: application/json
Authorization: Bearer {{otherToken}}

{
    "username": "APItest"
}

###
DELETE {{apiURL}}/boards/{{boardId}}
Authorization: Bearer {{otherToken}}
