
#@apiURL=http://localhost:8080
@apiURL={{$dotenv API_URL}}

###
POST {{apiURL}}/users/register
Content-Type: application/json

{
    "name": "APItest",
    "password": "Password123"
}

###
POST {{apiURL}}/users/login
Content-Type: application/json

{
    "name": "testuser",
    "password": "Password123"
}

###
POST {{apiURL}}/test

Content-Type: application/json

{
    "test": "TEST"
}